### ISSUE TITLE
Map control broken?

### ISSUE THREAD

**Issue by schneeb** [BrianErikson/KSP#1]
This seems to stop you controlling the craft from the map?

**Comment by BrianErikson** [comment]
What version of ksp are you using? If you downloaded it from CKAN within the last 24 hours or so, you may have inadvertently installed the wrong release.

**Comment by schneeb** [comment]
I'm on 1.1 pre (1.1.0.1183) - yes I got it from CKAN as it stated 1.1.0 was supported!

64bit windows 10 if that matters.

**Comment by BrianErikson** [comment]
Thanks for the report! I'll fix it today when i get off work

**Comment by BrianErikson** [comment]
@schneeb, see the new [release v0.2.1](https://github.com/BrianErikson/KSP/releases/tag/V0.2.1). I think CKAN only updates once a day -- so please check for it in CKAN on 6 Apr 2016.
